kafka:
  clusters:
    - name: training-kafka-cluster
      bootstrapServers: localhost:9092
      # schemaRegistryUrl: http://localhost:8081
      # kafkaConnect:
      #   - name: worker-1
      #     address: http://localhost:8083
